In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import platform
import pathlib

In [4]:
## Paths Input Here
if platform.uname().system == 'Darwin': #------------------------------Mac OS X---------------------------------------------------------------
    conn_path = r'/Users/cu135/Dropbox (Partners HealthCare)/memory/analyses/roi-roi_correl/matrix_corrMx_AvgR.csv'
    clin_path = r'/Users/cu135/Dropbox (Partners HealthCare)/memory/patient_data/AD_Clinical_Data_CDR_ADAS_COG_13.xlsx'
    # clin_path = 'path to clinical values'
    out_dir = r'/Users/cu135/Dropbox (Partners HealthCare)/memory/analyses/roi-roi_correl/figures/multidimensional_scatterplots'
    #out_dir = r'path to out dir here'
    x_roi_names = r'/Users/cu135/Dropbox (Partners HealthCare)/memory/analyses/roi-roi_correl/matrix_corrMx_names.csv'
    #roi_names = '<path to roi name location>'
    print('I have set pathnames in the Mac style')
else: #----------------------------------------------------------------Windows----------------------------------------------------------------
    conn_path = r'C:\Users\calvin.howard\Dropbox (Partners HealthCare)\memory\analyses\roi-roi_correl\matrix_corrMx_AvgR.csv'
    clin_path = r'C:\Users\calvin.howard\Dropbox (Partners HealthCare)\memory\patient_data\AD_Clinical_Data_CDR_ADAS_COG_13.xlsx'
    # clin_path = 'path to clinical values'
    out_dir = r'C:\Users\calvin.howard\Dropbox (Partners HealthCare)\memory\analyses\roi-roi_correl\stats'
    #out_dir = r'path to out dir here'
    x_roi_names = r'C:\Users\calvin.howard\Dropbox (Partners HealthCare)\memory\analyses\roi-roi_correl\matrix_corrMx_names.csv'
    #roi_names = '<path to roi name location>'
    print('I have set pathnames in the Windows style')

I have set pathnames in the Windows style

In [5]:
try:
    name_df = pd.read_csv(x_roi_names, names=['arb'], header=None)
    name_df.tail(5)
    colnames = name_df.arb.values.tolist()
    newname = []
    for name in colnames:
        arb = os.path.basename(name).split('.nii')[0]
        arb = arb[0:8]
        newname.append(arb)
    #print('NAMES: ', newname)

    x_df = pd.read_csv(conn_path, names=newname, header=None)#, ignore_index=True)
    x_df.index = newname
    x_df = x_df.iloc[8:,:8]
    x_df = x_df.reset_index(drop=True)
except:
    print('excepted')
    x_df = pd.read_csv(conn_path)
    colnames = x_df.columns.values
    newname = []
    for name in colnames:
        arb = os.path.basename(name).split('.nii')[0]
        arb = arb[0:8]
        newname.append(arb)
    x_df = x_df.set_axis(newname, axis=1, inplace=False)
    try:
        x_df.pop('Unnamed:')
    except:
        print('no x_df.pop(<name>) column to pop')


corr_df = x_df
corr_df.tail(3)

,00_memor,01_visua,02_somat,03_dorsa,04_ventr,05_limbi,06_front,07_defau
47,0.225163,-0.046054,-0.072667,-0.124370,-0.130400,0.302641,-0.127573,0.079391
48,0.228022,-0.041221,-0.076253,-0.123747,-0.141397,0.323542,-0.139500,0.074099
49,0.282438,-0.094408,-0.085608,-0.171892,-0.103193,0.225186,-0.077495,0.130953

In [6]:
#Assess connectivity values fundamentally
corr_description = corr_df.describe().transpose()
display(corr_description)

,count,mean,std,min,25%,50%,75%,max
00_memor,50.0,0.205354,0.044503,0.083375,0.174892,0.205535,0.234225,0.294498
01_visua,50.0,-0.045786,0.023526,-0.104341,-0.063749,-0.042132,-0.029745,0.001312
02_somat,50.0,-0.062143,0.020456,-0.107202,-0.078273,-0.059283,-0.047083,-0.027711
03_dorsa,50.0,-0.117958,0.031914,-0.184950,-0.138649,-0.115135,-0.096726,-0.030816
04_ventr,50.0,-0.116727,0.024494,-0.148808,-0.134395,-0.125414,-0.103286,-0.033823
05_limbi,50.0,0.283589,0.082985,-0.039611,0.245888,0.293108,0.334439,0.465591
06_front,50.0,-0.114568,0.041048,-0.172746,-0.146277,-0.126292,-0.087907,0.018306
07_defau,50.0,0.078468,0.033653,0.002173,0.058477,0.073367,0.097965,0.172278

In [7]:
#important metrics: 
# pt_id, randomization arm, age at DOS,
# baseline adas cog 11, baseline CDR
# %change adas cog 11, # change CDR


sheet_name = 'AD_Clinical_Scores'
alphab_cols = 'C, D, E, F, G, J, V'
clin_df = pd.read_excel(clin_path, sheet_name=sheet_name, usecols=alphab_cols, nrows=50)
print('Num NaNs: ', clin_df.isna().sum().sum())
# clin_df.tail(5)
display(clin_df[::2])

Num NaNs:  32

,Randomization Arm,"Patient # CDR, ADAS",Age at DOS,Baseline ADAS-Cog11,Baseline CDR (sum of squares),% Change from baseline (ADAS-Cog11),% Change from baseline (CDR)
0,sham-stim,101,62,28.0,5.0,-21.428571,-40.000000
2,sham-stim,103,76,19.0,7.0,-78.947368,-42.857143
4,NaN,105,50,19.0,NaN,-10.526316,NaN
6,NaN,107,64,13.0,NaN,-15.384615,NaN
8,sham-stim,109,72,23.0,9.0,-30.434783,-44.444444
10,NaN,111,62,12.0,NaN,41.666667,NaN
12,stim-sham,113,69,15.0,5.5,-60.000000,-100.000000
14,NaN,115,60,29.0,NaN,-48.275862,NaN
16,sham-stim,118,52,32.0,6.0,-3.125000,-100.000000
18,NaN,1201,78,19.6,NaN,-7.142857,NaN
20,NaN,1203,76,24.0,NaN,-73.333333,NaN
22,sham-stim,121,72,23.0,5.5,-4.347826,-118.181818
24,sham-stim,123,47,22.0,5.0,54.545455,10.000000
26,stim-sham,125,73,16.0,4.0,-37.500000,-75.000000
28,sham-stim,127,74,17.0,5.0,-76.470588,-80.000000
30,sham-stim,129,69,28.0,5.5,-35.714286,-100.000000
32,stim-sham,131,68,20.0,3.5,-40.000000,0.000000
34,stim-sham,134,66,17.0,3.5,29.411765,0.000000
36,stim-sham,137,57,22.0,6.5,-77.272727,-38.461538
38,sham-stim,139,58,17.0,2.0,-105.882353,-100.000000
40,sham-stim,141,72,19.0,9.0,0.000000,11.111111
42,sham-stim,143,71,16.0,3.0,6.250000,-16.666667
44,stim-sham,145,74,18.0,3.5,5.555556,-100.000000
46,stim-sham,147,59,21.0,3.0,-4.761905,-100.000000
48,sham-stim,149,77,10.0,5.0,-90.000000,-20.000000

In [8]:
## Organize the clinical dataframe
clin_df = clin_df.sort_values(by=['Patient # CDR, ADAS'], kind='quicksort', axis=0, ascending=True, ignore_index=True)
clin_df.tail(10)

,Randomization Arm,"Patient # CDR, ADAS",Age at DOS,Baseline ADAS-Cog11,Baseline CDR (sum of squares),% Change from baseline (ADAS-Cog11),% Change from baseline (CDR)
40,stim-sham,144,79,13.0,3.0,-61.538462,-133.333333
41,stim-sham,145,74,18.0,3.5,5.555556,-100.000000
42,sham-stim,146,76,11.0,4.0,-54.545455,-50.000000
43,stim-sham,147,59,21.0,3.0,-4.761905,-100.000000
44,stim-sham,148,51,13.0,3.5,-207.692308,-157.142857
45,sham-stim,149,77,10.0,5.0,-90.000000,-20.000000
46,sham-stim,150,71,22.0,4.5,13.636364,0.000000
47,NaN,1201,78,19.6,NaN,-7.142857,NaN
48,NaN,1202,74,13.3,NaN,-2.255639,NaN
49,NaN,1203,76,24.0,NaN,-73.333333,NaN

In [9]:
##One-hot-encode the dataframe | sham=0 stim=1 
shams = (clin_df['Randomization Arm'] == 'sham-stim')
clin_df.loc[shams, 'Randomization Arm'] = 0
stims = (clin_df['Randomization Arm'] == 'stim-sham')
clin_df.loc[stims, 'Randomization Arm'] = 1
clin_df.tail(10)

,Randomization Arm,"Patient # CDR, ADAS",Age at DOS,Baseline ADAS-Cog11,Baseline CDR (sum of squares),% Change from baseline (ADAS-Cog11),% Change from baseline (CDR)
40,1,144,79,13.0,3.0,-61.538462,-133.333333
41,1,145,74,18.0,3.5,5.555556,-100.000000
42,0,146,76,11.0,4.0,-54.545455,-50.000000
43,1,147,59,21.0,3.0,-4.761905,-100.000000
44,1,148,51,13.0,3.5,-207.692308,-157.142857
45,0,149,77,10.0,5.0,-90.000000,-20.000000
46,0,150,71,22.0,4.5,13.636364,0.000000
47,NaN,1201,78,19.6,NaN,-7.142857,NaN
48,NaN,1202,74,13.3,NaN,-2.255639,NaN
49,NaN,1203,76,24.0,NaN,-73.333333,NaN

In [10]:
## Develop Understanding of the Clinical Data
try:
    clin_description = clin_df.describe().transpose()
    display(clin_description)
except:
    print('Failed to describe clinical dataframe, unknown cause')

,count,mean,std,min,25%,50%,75%,max
"Patient # CDR, ADAS",50.0,189.920000,258.695695,101.000000,113.250000,126.500000,140.750000,1203.000000
Age at DOS,50.0,67.480000,7.985293,47.000000,62.000000,69.000000,73.750000,79.000000
Baseline ADAS-Cog11,50.0,19.238000,5.600688,10.000000,15.250000,18.500000,22.000000,35.000000
Baseline CDR (sum of squares),40.0,4.787500,1.727929,1.000000,3.500000,5.000000,5.500000,9.000000
% Change from baseline (ADAS-Cog11),50.0,-35.563519,48.852186,-207.692308,-61.153846,-28.472222,-3.430707,54.545455
% Change from baseline (CDR),38.0,-73.831483,79.163640,-400.000000,-100.000000,-59.615385,-21.250000,11.111111

In [11]:
corrd_df = corr_df.reset_index()
total_df = pd.concat([clin_df, corr_df], axis=1)
display(total_df)

,Randomization Arm,"Patient # CDR, ADAS",Age at DOS,Baseline ADAS-Cog11,Baseline CDR (sum of squares),% Change from baseline (ADAS-Cog11),% Change from baseline (CDR),00_memor,01_visua,02_somat,03_dorsa,04_ventr,05_limbi,06_front,07_defau
0,0,101,62,28.0,5.0,-21.428571,-40.000000,0.155809,-0.016067,-0.037287,-0.097985,-0.133136,0.368843,-0.161642,0.050232
1,1,102,77,22.0,6.5,-36.363636,-69.230769,0.173658,-0.039878,-0.032239,-0.129030,-0.131156,0.465591,-0.171597,0.077686
2,0,103,76,19.0,7.0,-78.947368,-42.857143,0.191375,-0.032546,-0.036808,-0.118963,-0.139225,0.368452,-0.161276,0.082011
3,1,104,65,17.0,7.0,-129.411765,-71.428571,0.159578,-0.015783,-0.062662,-0.088505,-0.130241,0.322597,-0.139443,0.039187
4,NaN,105,50,19.0,NaN,-10.526316,NaN,0.144300,-0.048057,-0.090870,-0.085284,-0.078547,0.215256,-0.057259,0.028220
5,1,106,66,13.0,3.0,-38.461538,-50.000000,0.197998,-0.022790,-0.044253,-0.106363,-0.144834,0.327426,-0.157877,0.072634
6,NaN,107,64,13.0,NaN,-15.384615,NaN,0.154363,-0.042301,-0.086612,-0.089494,-0.096292,0.244718,-0.085726,0.031619
7,NaN,108,60,24.0,NaN,-29.166667,NaN,0.163638,-0.053981,-0.097731,-0.099889,-0.088261,0.232628,-0.065393,0.042303
8,0,109,72,23.0,9.0,-30.434783,-44.444444,0.239486,-0.064388,-0.052075,-0.148891,-0.134814,0.352712,-0.137391,0.113133
9,0,110,72,13.0,5.0,-84.615385,-80.000000,0.207923,-0.041962,-0.056562,-0.104225,-0.112208,0.215980,-0.097356,0.076609
10,NaN,111,62,12.0,NaN,41.666667,NaN,0.173987,-0.029551,-0.051557,-0.074061,-0.083969,0.139782,-0.063055,0.058412
11,NaN,112,69,15.0,NaN,9.333333,NaN,0.208818,-0.053266,-0.050448,-0.113176,-0.101460,0.221584,-0.087603,0.091283
12,1,113,69,15.0,5.5,-60.000000,-100.000000,0.189567,-0.029871,-0.058701,-0.102870,-0.132524,0.298926,-0.132376,0.066159
13,0,114,67,31.0,7.0,-16.129032,0.000000,0.182893,-0.032639,-0.072636,-0.107711,-0.126536,0.310364,-0.126784,0.058675
14,NaN,115,60,29.0,NaN,-48.275862,NaN,0.167374,-0.055260,-0.107202,-0.094966,-0.064964,0.183809,-0.032866,0.047150
15,1,116,67,19.0,4.0,-36.842105,-37.500000,0.203776,-0.029475,-0.055087,-0.116742,-0.138410,0.346851,-0.153224,0.069970
16,0,118,52,32.0,6.0,-3.125000,-100.000000,0.199587,-0.063874,-0.081367,-0.101112,-0.033823,-0.039611,0.018306,0.069975
17,1,119,75,16.0,5.0,-81.250000,-100.000000,0.214016,-0.051740,-0.046758,-0.136527,-0.137780,0.369191,-0.148438,0.098431
18,NaN,120,68,18.0,NaN,-27.777778,NaN,0.083375,-0.013256,-0.061238,-0.030816,-0.069480,0.176052,-0.048898,0.002173
19,0,121,72,23.0,5.5,-4.347826,-118.181818,0.121628,-0.022520,-0.061091,-0.070508,-0.106057,0.261587,-0.107099,0.033141
20,1,122,58,15.0,5.0,-140.000000,NaN,0.135280,0.001312,-0.038787,-0.075092,-0.129807,0.307567,-0.156778,0.027834
21,0,123,47,22.0,5.0,54.545455,10.000000,0.236313,-0.070222,-0.049280,-0.143950,-0.108161,0.279170,-0.106232,0.114561
22,1,124,61,16.0,5.0,-18.750000,-20.000000,0.268610,-0.078439,-0.065838,-0.163538,-0.111440,0.301627,-0.108637,0.123637
23,1,125,73,16.0,4.0,-37.500000,-75.000000,0.267958,-0.075037,-0.054662,-0.168336,-0.135086,0.363546,-0.140429,0.130170
24,1,126,69,21.0,5.0,-100.000000,-240.000000,0.248741,-0.065697,-0.047890,-0.161016,-0.143597,0.406549,-0.158014,0.120742
25,0,127,74,17.0,5.0,-76.470588,-80.000000,0.166208,-0.015701,-0.045936,-0.094790,-0.136605,0.340841,-0.156796,0.050417
26,0,128,72,24.0,7.0,-20.833333,-28.571429,0.267084,-0.077313,-0.078946,-0.166488,-0.124292,0.329518,-0.118158,0.116442
27,0,129,69,28.0,5.5,-35.714286,-100.000000,0.237566,-0.063376,-0.084900,-0.136369,-0.119300,0.275608,-0.099296,0.090705
28,1,130,66,14.0,2.0,-7.142857,-25.000000,0.196261,-0.029704,-0.057873,-0.102844,-0.127596,0.287290,-0.127107,0.065404
29,1,131,68,20.0,3.5,-40.000000,0.000000,0.192844,-0.030486,-0.059865,-0.096306,-0.119888,0.249400,-0.111284,0.064367
30,0,133,74,16.0,4.5,6.250000,NaN,0.242778,-0.058518,-0.070772,-0.134188,-0.112548,0.254315,-0.100198,0.096566
31,1,134,66,17.0,3.5,29.411765,0.000000,0.229116,-0.041493,-0.053164,-0.130955,-0.139869,0.346565,-0.151155,0.090347
32,0,135,57,35.0,4.5,-45.714286,-211.111111,0.209367,-0.041526,-0.083472,-0.117396,-0.129324,0.313305,-0.121897,0.068451
33,1,137,57,22.0,6.5,-77.272727,-38.461538,0.207293,-0.036691,-0.061281,-0.107301,-0.116571,0.257623,-0.110817,0.071194
34,1,138,72,21.0,4.5,-9.523810,-77.777778,0.268621,-0.093497,-0.103810,-0.162371,-0.084257,0.168606,-0.046824,0.116485
35,0,139,58,17.0,2.0,-105.882353,-100.000000,0.180696,-0.021666,-0.052125,-0.092107,-0.119865,0.282953,-0.125799,0.053391
36,1,140,73,22.0,4.0,18.181818,0.000000,0.201308,-0.033303,-0.062765,-0.108146,-0.133128,0.315241,-0.132625,0.066960
37,0,141,72,19.0,9.0,0.000000,11.111111,0.229930,-0.052606,-0.079322,-0.122774,-0.103564,0.229931,-0.088820,0.078665
38,1,142,77,18.0,1.0,5.555556,-400.000000,0.229603,-0.048487,-0.042011,-0.139357,-0.145307,0.375950,-0.160136,0.104946
39,0,143,71,16.0,3.0,6.250000,-16.666667,0.284269,-0.104341,-0.096958,-0.184950,-0.090461,0.253544,-0.069136,0.130643
40,1,144,79,13.0,3.0,-61.538462,-133.333333,0.213704,-0.059516,-0.046815,-0.113528,-0.082743,0.139836,-0.066079,0.094708
41,1,145,74,18.0,3.5,5.555556,-100.000000,0.177606,-0.016419,-0.037271,-0.087153,-0.130737,0.275142,-0.138697,0.061912
42,0,146,76,11.0,4.0,-54.545455,-50.000000,0.294498,-0.066966,-0.027711,-0.179376,-0.148808,0.392472,-0.172746,0.172278
43,1,147,59,21.0,3.0,-4.761905,-100.000000,0.148442,-0.003548,-0.035964,-0.074463,-0.128114,0.284857,-0.144433,0.038839
44,1,148,51,13.0,3.5,-207.692308,-157.142857,0.235194,-0.064897,-0.095827,-0.139808,-0.096939,0.255358,-0.080122,0.085270
45,0,149,77,10.0,5.0,-90.000000,-20.000000,0.198296,-0.035910,-0.065456,-0.118099,-0.136036,0.336080,-0.146891,0.069742
46,0,150,71,22.0,4.5,13.636364,0.000000,0.231318,-0.064349,-0.030728,-0.140072,-0.123597,0.322457,-0.127742,0.125290
47,NaN,1201,78,19.6,NaN,-7.142857,NaN,0.225163,-0.046054,-0.072667,-0.124370,-0.130400,0.302641,-0.127573,0.079391
48,NaN,1202,74,13.3,NaN,-2.255639,NaN,0.228022,-0.041221,-0.076253,-0.123747,-0.141397,0.323542,-0.139500,0.074099
49,NaN,1203,76,24.0,NaN,-73.333333,NaN,0.282438,-0.094408,-0.085608,-0.171892,-0.103193,0.225186,-0.077495,0.130953

In [12]:
#Handle NaNs
total_df = total_df.fillna(method='ffill')
print('Num NaNs: ', total_df.isna().sum().sum())

Num NaNs:  0

In [13]:
#Generate metrics for udnerstanding
try:
    total_desc = total_df.describe().transpose()
    total_desc
except:
    print('Failed to generate total metrics, unkown cause')

## Chi Squared Test Time

In [14]:
## Choose variables of interest.
x_name = '00_memor'
z_name = '% Change from baseline (ADAS-Cog11)' #--------------------------------------------------------This variable is the outcome variable

x_vals = total_df[x_name]
z_vals = total_df[z_name]#------------------------------------------------------------------------------This variable is the outcome variable


#subgrouping by age
metric = 'Age at DOS'
metric_val = 65

index_one = (total_df[metric] > metric_val) #example, all individuals over 65
index_two = (total_df[metric] <= metric_val) #example, all individuals under/equal to 65

##Example of how to use these indices to manipulate data:
#### clin_df.loc[index_one, '<names of relevant columns>'] = 0 ## can use iloc too.

In [73]:
## BIN THE DATA BY PROBABILITY
import scipy.stats as st

x_zscore = st.zscore(x_vals)
y_zscore = st.zscore(z_vals)

z1 = st.norm.ppf(.25); z2 = st.norm.ppf(.5); z3 = st.norm.ppf(.75); z4 = st.norm.ppf(0.99999)
print(z1, z2, z3, z4)

#Prepare the datframe from contingency table creation
xbins = (x_zscore<=z2); ybins = (y_zscore<=z2)
xbins[xbins == True] = '<=z2'; ybins[ybins == True] = '<=z2'
xbins[xbins == False] = '>z2'; ybins[ybins == False] = '>z2'
total_df['xbins'] = xbins; total_df['ybins'] = ybins

#CALCULATE MARGINS OF THE CONTINGENCY TABLE
xbin1 = np.count_nonzero(x_zscore<=z2); xbin2 = np.count_nonzero(x_zscore >z2); #xbin3 = np.count_nonzero((x_zscore>z2) & (x_zscore<=z3)); xbin4 = np.count_nonzero(x_zscore>z3)
ybin1 = np.count_nonzero(y_zscore<=z2); ybin2 = np.count_nonzero(y_zscore >z2); # ybin3 = np.count_nonzero((y_zscore>z2) & (y_zscore<=z3)); ybin4 = np.count_nonzero(y_zscore>z3)

#CALCULATE OBSERVED VALUES OF THE CONTINGENCY TABLE
or1c1 = np.count_nonzero(total_df.index[(total_df['xbins'] == '<=z2') & (total_df['ybins'] == '<=z2')])+1
or2c1 = np.count_nonzero(total_df.index[(total_df['xbins'] == '>z2') & (total_df['ybins'] == '<=z2')])
or1c2 = np.count_nonzero(total_df.index[(total_df['xbins'] == '<=z2') & (total_df['ybins'] == '>z2')])
or2c2 = np.count_nonzero(total_df.index[(total_df['xbins'] == '>z2') & (total_df['ybins'] == '>z2')])
print(or1c1, or2c1, or1c2, or2c2) #, np.sum(r1c1, r2c1, r1c2, r2c2))

#CALCULATE THE EXPECTED VALUES OF THE CONTINGENCY TRABLE
er1c1 = xbin1*ybin1/len(total_df.index); 
er2c1 = xbin2*ybin1/len(total_df.index); 
er1c2 = xbin1*ybin2/len(total_df.index); 
er2c2 = xbin2*ybin2/len(total_df.index)
print(er1c1, er2c1, er1c2, er2c2)

cont_table_df = pd.DataFrame({'<=50% outcomes by prob': [or1c1, or2c1],
                            '>50% outcomes by prob': [or1c2, or2c2]}, index=['<=50% connect by prob', '>50% connect by prob'])

exp_table_df = pd.DataFrame({'<=50% outcomes by prob': [er1c1, er2c1],
                            '>50% outcomes by prob': [er1c2, er2c2]}, index=['<=50% connect by prob', '>50% connect by prob'])

##----------------------------------------------------------------
#THE ERROR IN THIS CODE IS THAT i NEED TO CALCULATE THE BINS FOR THE INTERSECTIONS OF EACH DATA GROUP
#SO, I NEED THE 'LOW PROB CONN AND HIGH PROB OUTCOME' BIN COUNT, ETC, FOR EACH. 
#NOW, WITH MY LOW LUMBERS, THIS CREATES 16 BINS, AND 50/16 = ~3.7, WHICH IS <5, THEREFOR CHI IS NOT APPLICABLE AND FISHER IS REQUIRED. 
#CAN CHANGE TO BING 4X2, AND 50/8=~6.25, WHICH IS STILL AT RISK OF <5 IN LOW/LOW PROB BINS, MEANING FISHER IS REQUIRED STILL.
#CAN CHANGE BIN TO 2X2, AND 50/4 = 12.5, WHICH IS MUCH SAFER. 
##----------------------------------------------------------------


#Bin by Quantile
# quantile = 0.25
# outcome = np.quantile(total_df[z_name], quantile)
# conn = np.quantile(total_df[x_name], quantile)
display(cont_table_df)

-0.6744897501960817 0.0 0.6744897501960817 4.264890793923841
13 11 12 14
11.5 11.5 13.5 13.5

                       <=50% outcomes by prob  >50% outcomes by prob
<=50% connect by prob                      13                     12
>50% connect by prob                       11                     14

In [74]:
display(exp_table_df)

                       <=50% outcomes by prob  >50% outcomes by prob
<=50% connect by prob                    11.5                   13.5
>50% connect by prob                     11.5                   13.5

In [81]:
#Chi Square Calculation
#----------------------------------------------------------------can calculate the chi-squared value by hand by: sum[(obs-exp)^2/exp]
#TBD

#----------------------------------------------------------------Or, can use scipy to calculate the chi-squared
from scipy.stats import chi2_contingency
table = np.array([[int(or1c1), int(or1c2)], [int(or2c1), int(or2c2)]])
stat, p, dof, exp_table2= chi2_contingency(table)
outcomes_df = cont_table_df
outcomes_df['p_val'] = p
outcomes_df['chisq_stat'] = stat
outcomes_df['dof'] = dof

#DEPRECATED, NOT CONFIDENT IN MATHEMATICS
# from scipy.stats import chisquare
# table = np.array([[xbin1, xbin2, xbin3, xbin4], [ybin1, ybin2, ybin3, ybin4]])
# chisq, p = chisquare(table, axis=None)
# print(p)
# outcomes_df = pd.DataFrame({'Probability Bins X': [xbin1, xbin2, xbin3, xbin4], 
#                         'Probability Bins Y': [ybin1, ybin2, ybin3, ybin4],
#                         'ChiSq Vals': chisq,
#                         'P Vals': p}, 
#                         index=['0.25>prob', '0.25<prob<0.5', '0.5<prob<0.75', '0.75<prob'])

display(outcomes_df)

,<=50% outcomes by prob,>50% outcomes by prob,p_val,chisq_stat,dof
<=50% connect by prob,13,12,0.777124,0.080128,1
>50% connect by prob,11,14,0.777124,0.080128,1

In [82]:
#Save outcomes
figname = 'chisquared_' + x_name + '_by_' + z_name + '_' + '2_probability_bins_1p_derived_from_contingency_table'
if os.path.isdir(out_dir) != True:
    os.mkdir(out_dir)
outcomes_df.to_csv(os.path.join(out_dir, (figname+'.csv')))
print(f'{figname} saved to: \n {out_dir}')

chisquared_00_memor_by_% Change from baseline (ADAS-Cog11)_2_probability_bins_1p_derived_from_contingency_table saved to:
 C:\Users\calvin.howard\Dropbox (Partners HealthCare)\memory\analyses\roi-roi_correl\stats