In [6]:
path_1 = '/Users/cu135/Dropbox (Partners HealthCare)/studies/atrophy_seeds_2023/metadata/bl_adas_scores.csv'
path_2 = '/Users/cu135/Dropbox (Partners HealthCare)/studies/atrophy_seeds_2023/metadata/master_list_z_only.csv'

In [7]:
import pandas as pd
df1 = pd.read_csv(path_1)
df2 = pd.read_csv(path_2)
df2

,subject,CerebellumSBM,CerebellumCSF,CerebellumGM,CerebellumWM,FrontalSurface,FrontalCSF,FrontalGM,FrontalWM,InsularSurface,...,ventricle,cerebellar_vermis,cerebellar_fissures,frontal_eh,temporal_eh,parietal_eh,occipital_eh,cerebellum_eh,mesial temporal_eh,ventricle_eh
0,1,0,-4497.364934,980.567621,2977.241279,-30.976181,-9854.189802,-2592.141866,15981.602420,0.000000,...,0,0,0,0,0,0,0,0,1,0
1,2,0,-2201.458697,-18138.572720,-11183.039810,-36.083698,-9149.893654,-26395.833840,-16728.096790,-4.145363,...,1,1,1,1,0,1,1,1,1,1
2,3,0,5422.499148,-5613.118199,9831.510960,-104.795906,13796.400820,-18396.096240,4236.306518,0.000000,...,2,0,0,1,2,1,0,0,2,2
3,4,0,10039.542490,4899.249983,6559.417793,-252.720785,10684.093530,-9280.278454,16906.567050,-2.313154,...,2,0,2,0,1,0,0,0,2,1
4,5,0,-807.610765,-10722.003290,-7145.779641,-48.613606,-5685.897742,-16940.901910,-6925.515179,-4.794878,...,0,0,2,0,1,1,0,0,2,0
5,6,0,-2512.170377,-1056.173682,2425.407108,-92.413730,-4723.426224,-6500.935230,9211.785284,-3.640567,...,0,0,1,0,2,2,0,0,1,0
6,7,0,-3810.571029,2017.963719,2364.859302,-72.367939,-5452.430173,3952.113561,4915.163107,0.000000,...,2,1,1,1,2,2,1,1,1,1
7,8,0,-1377.764614,-301.016853,1047.897930,-257.644674,4570.889094,3721.107713,13588.501410,-15.507745,...,2,0,1,2,1,0,0,0,4,2
8,9,0,21528.922020,10057.371230,15527.412260,-165.863003,24748.663740,8417.850048,17625.209260,-2.043447,...,2,1,2,1,1,2,0,1,3,2
9,10,0,-331.479770,-6104.352219,580.351404,-22.831228,-1913.363895,1692.824389,8063.496605,-3.357940,...,1,0,1,0,1,1,0,0,0,0
10,11,0,9869.486016,11122.342400,-895.478236,-86.666695,17608.845400,20688.027740,11112.854390,0.000000,...,2,1,2,1,2,1,0,1,3,2
11,12,0,4717.085594,16826.353680,13884.914220,-137.724410,10017.086990,19402.827040,11341.775500,-6.575785,...,2,0,2,1,2,2,0,0,1,1
12,13,0,-1199.497876,-19962.179850,-14307.885460,-81.470232,-6091.241026,-16573.059910,-14511.796900,-12.376970,...,2,0,2,1,2,2,1,0,1,1
13,14,0,1505.740371,1834.647957,11441.559620,-260.507399,11500.925660,-11917.766050,4810.739465,-4.936501,...,2,0,1,1,2,1,0,0,2,1
14,15,0,-2138.697112,11485.524060,8944.047318,-34.296010,3958.961232,8319.639296,8413.126989,0.000000,...,1,0,1,1,1,1,1,0,0,1
15,16,0,3786.179144,-3432.225779,4813.191631,-112.079015,451.627930,-1587.288273,21575.294040,-4.617155,...,0,0,1,0,0,1,0,0,0,0
16,17,0,7603.158068,-1516.198249,1050.849621,-65.192509,22814.774920,10082.905480,8241.878144,-8.583321,...,1,1,1,1,2,1,1,1,3,1
17,18,0,4112.348942,-4522.095084,-8312.880945,-91.675593,13779.898060,-10242.476120,-5966.339646,-4.506109,...,2,0,1,1,2,1,0,0,3,2
18,19,0,-4559.982453,-2306.715670,-6252.112247,-31.608093,-3526.163105,6144.537889,4015.608531,-10.554750,...,0,0,0,1,1,1,0,0,0,0
19,20,0,-7629.796469,-1568.993475,915.804551,-35.703737,-10044.546640,11087.465950,17808.474990,-2.150845,...,0,0,0,0,0,0,0,0,0,0
20,21,0,5526.185830,22452.092720,14570.054120,-52.295274,19140.690400,17671.054580,25126.580250,-4.120685,...,2,1,2,2,1,3,0,1,4,1
21,22,0,6835.044151,13134.277280,5918.253242,-38.561811,10518.274600,4042.628162,180.395935,0.000000,...,2,1,2,1,1,2,1,1,3,2
22,23,0,-7917.877719,2829.108559,-2091.997116,-18.170561,-15082.353820,4191.354112,4036.167384,-2.273662,...,0,0,1,0,0,1,0,0,1,0
23,24,0,4871.868954,5714.418470,4327.271552,-93.567752,3605.186881,24796.708190,14008.245160,-11.832618,...,1,0,1,0,1,1,0,0,2,1
24,25,0,584.186317,593.786472,-328.309038,-120.186539,-4318.369043,-8410.281330,5545.971836,-9.028558,...,1,0,0,0,2,1,1,0,2,2
25,26,0,140.358298,-2790.885944,-7229.608020,-36.458639,3868.937890,-16348.602200,-7213.338886,0.000000,...,1,0,1,1,2,2,1,0,2,1
26,27,0,6842.889851,1829.611557,2845.852721,-55.963174,32409.225480,32696.493660,19451.466500,-2.145772,...,2,0,1,1,1,2,0,0,3,2
27,28,0,-362.152382,15498.240640,8462.338620,-22.204505,3227.715573,36997.985770,27442.767550,0.000000,...,1,0,2,1,0,1,0,0,0,1
28,29,0,-579.449091,-4457.028976,-4584.381484,-150.486269,1724.975248,-13969.310430,-3174.852195,-7.015039,...,0,0,1,0,2,1,1,0,2,0
29,30,0,-39.253529,-3875.987928,-6736.100139,-79.655200,-2528.287915,-16161.459660,-7905.077616,-2.169010,...,1,0,2,1,2,1,0,0,2,1
30,31,0,-2726.979906,-8123.317974,-2699.443537,-18.417506,-8983.663847,-7647.710417,1456.834638,0.000000,...,0,0,1,1,0,1,0,0,0,0
31,32,0,6642.389242,5018.559162,1857.476388,-22.695699,26513.315130,17404.061190,13128.701330,-2.448552,...,2,1,2,1,2,2,1,1,4,2
32,33,0,634.183060,-714.222526,4729.156976,-108.472697,8093.889995,-269.409785,22577.763390,0.000000,...,0,0,3,1,2,2,0,0,2,0
33,34,0,-2465.338531,-1864.715981,2686.673946,-25.477848,-6713.509834,2453.344085,-6162.799090,-2.881592,...,0,0,1,0,0,1,0,0,1,0
34,35,0,3555.800211,14753.220180,-150.872161,-242.753904,17148.432800,799.463774,15418.381470,-23.334179,...,2,0,2,1,2,1,0,0,2,2
35,36,0,3662.913619,25114.113290,21345.037160,-102.211027,5618.037817,15431.461800,23032.918860,-6.700692,...,0,0,1,0,1,1,0,0,2,0
36,37,0,-8765.419115,-14359.589150,-6846.536868,-58.914601,-16935.218110,13903.760880,296.867440,-2.016903,...,0,0,0,0,0,0,0,0,1,0
37,38,0,2521.557181,12100.739480,417.469514,-102.246471,11742.379690,5088.720537,-103.936259,-2.703633,...,1,0,1,1,1,2,0,0,1,1
38,39,0,-3491.481790,-2887.488762,-4124.295062,-29.664265,-2090.066558,243.428552,-4357.417470,-5.475521,...,1,0,1,1,1,1,1,0,3,1
39,40,0,4501.390785,14086.366130,10089.115110,-58.658250,11756.146820,29855.017680,27764.291620,-7.389536,...,1,0,0,1,1,2,0,0,1,1
40,41,0,9090.831006,-8203.018071,3937.388504,-244.496132,8036.921762,-21071.482220,4475.087802,-22.125416,...,0,0,2,0,1,0,0,0,2,0
41,42,0,4697.908300,-6542.625302,2982.377927,-323.563475,12666.571450,-19120.601390,7222.117208,-8.989416,...,2,1,2,2,2,2,1,1,3,2
42,43,0,1127.841143,-9308.785805,-8742.807780,-55.187397,6025.086804,-1165.535088,-2027.875705,-2.079455,...,0,0,1,1,2,1,0,0,1,0
43,44,0,-2348.541294,-3030.575610,-1952.084806,-335.655284,-3175.294289,5612.834128,-5312.765393,0.000000,...,3,0,1,0,0,1,0,0,1,3
44,45,0,7221.251020,5021.810228,1499.685479,-33.856108,5405.563481,2025.419643,15187.370340,0.000000,...,0,1,1,1,1,2,0,1,0,0
45,46,0,-3961.355104,-24031.910070,-9109.204510,-192.463318,-4703.781559,-40740.635520,-11328.841710,-13.848285,...,1,0,2,0,1,1,1,0,1,1
46,47,0,5056.305591,-3548.124638,482.194832,-116.596988,-2834.427986,-2232.282375,2153.935846,0.000000,...,1,0,2,1,1,1,1,0,3,1
47,48,0,5243.802177,4984.295131,5586.470819,-109.097904,13527.445630,-4125.723466,13711.862090,-4.460277,...,1,0,1,0,1,1,1,0,2,1
48,49,0,-2735.743492,-26412.015930,-2040.272422,-187.581870,-5532.505653,-31899.326300,504.884462,-4.179206,...,1,0,2,0,1,1,0,0,1,1
49,50,0,1887.333795,-1577.954777,-3398.982892,-27.574568,-990.640509,7074.137496,3076.111578,-2.285043,...,0,0,1,0,0,1,0,0,1,0

In [9]:
merged_df = pd.merge(df1, df2, on='subject', how='inner')
merged_df

,PTID,SITEID,VISCODE,USERDATE,EXAMDATE,Q1,Q2,Q3,Q4,Q5,...,ventricle,cerebellar_vermis,cerebellar_fissures,frontal_eh,temporal_eh,parietal_eh,occipital_eh,cerebellum_eh,mesial temporal_eh,ventricle_eh
0,024_S_1393,12,bl,8/20/14,4/20/07,5.00,0,1,9,0,...,2,0,1,2,1,0,0,0,4,2
1,941_S_1202,127,bl,8/20/14,2/12/07,3.67,0,0,6,0,...,2,0,2,1,2,2,0,0,1,1
2,009_S_1199,105,bl,8/20/14,1/26/07,6.33,0,0,7,1,...,0,0,1,0,1,1,0,0,2,0
3,141_S_1152,19,bl,8/20/14,1/8/07,4.00,0,1,9,1,...,2,0,2,1,2,2,1,0,1,1
4,126_S_1077,113,bl,8/20/14,12/19/06,5.67,0,1,7,0,...,2,0,1,1,2,1,0,0,2,1
5,005_S_0929,1,bl,8/20/14,11/8/06,3.67,0,0,7,0,...,2,1,2,2,2,2,1,1,3,2
6,029_S_0871,14,bl,8/20/14,1/11/07,3.67,0,0,6,0,...,1,0,1,0,1,1,0,0,2,1
7,002_S_0816,101,bl,8/20/14,9/11/06,5.00,0,0,8,0,...,1,0,2,1,1,1,1,0,3,1
8,016_S_0769,111,bl,8/20/14,8/31/06,3.33,0,1,3,1,...,2,1,2,2,1,3,0,1,4,1
9,062_S_0768,30,bl,8/20/14,8/23/06,5.33,1,0,4,1,...,2,1,2,1,1,2,0,1,3,2
10,137_S_0722,124,bl,8/20/14,9/1/06,3.67,0,1,5,0,...,1,0,0,1,1,2,0,0,1,1
11,036_S_0656,17,bl,8/20/14,7/27/06,6.33,0,1,7,0,...,0,0,1,1,2,1,0,0,1,0
12,023_S_0613,11,bl,8/20/14,7/24/06,6.67,1,1,6,1,...,1,0,1,1,2,2,1,0,2,1
13,014_S_0558,110,bl,8/20/14,7/6/06,3.67,0,1,7,0,...,2,0,2,0,1,0,0,0,2,1
14,094_S_0526,41,bl,8/20/14,5/25/05,1.33,0,1,1,1,...,1,0,2,0,1,1,0,0,1,1
15,037_S_0467,18,bl,8/20/14,6/13/06,2.00,0,0,2,0,...,2,1,1,1,2,2,1,1,1,1
16,114_S_0378,87,bl,8/20/14,4/24/06,3.67,0,0,6,0,...,1,0,1,1,1,1,1,0,3,1
17,123_S_0298,94,bl,8/20/14,4/27/06,1.33,0,0,2,0,...,0,0,1,0,2,2,0,0,1,0
18,005_S_0223,1,bl,8/20/14,3/24/06,3.33,0,1,2,0,...,0,0,2,0,1,0,0,0,2,0
19,114_S_0173,87,bl,8/20/14,2/22/06,1.67,0,0,1,0,...,1,0,1,0,1,1,1,0,2,1
20,027_S_0120,13,bl,8/20/14,2/16/06,4.33,0,1,4,0,...,0,0,1,0,0,1,0,0,0,0
21,007_S_0101,2,bl,8/20/14,1/4/06,4.00,0,0,4,0,...,2,0,2,1,2,1,0,0,2,2
22,023_S_0084,11,bl,8/20/14,1/24/06,6.00,0,0,9,0,...,1,0,2,1,2,1,0,0,2,1
23,007_S_0068,2,bl,8/20/14,12/15/05,1.00,0,1,1,0,...,0,0,1,0,2,1,1,0,2,0
24,128_S_1430,115,bl,8/20/14,9/21/07,5.00,0,2,8,1,...,1,0,2,0,1,1,1,0,1,1
25,012_S_4012,9,bl,5/2/11,2/12/13,2.00,0,0,2,0,...,0,0,1,0,0,1,0,0,1,0
26,024_S_4169,18,bl,8/29/11,10/21/11,2.00,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,033_S_4176,23,bl,9/7/11,NaN,2.00,0,1,1,0,...,1,1,1,1,2,1,1,1,3,1
28,067_S_4184,32,bl,9/22/11,NaN,2.00,1,0,1,0,...,0,0,1,0,0,1,0,0,1,0
29,006_S_4192,4,bl,10/6/11,10/24/11,5.00,0,0,7,0,...,2,0,1,1,2,1,0,0,3,2
30,002_S_4270,1,bl,11/1/11,NaN,3.00,0,1,2,0,...,0,0,1,1,0,1,0,0,0,0
31,130_S_4343,50,bl,11/16/11,5/9/12,5.00,0,0,7,0,...,1,0,1,0,1,1,0,0,0,0
32,018_S_4313,13,bl,11/30/11,NaN,5.00,0,0,4,0,...,0,0,0,1,1,1,0,0,0,0
33,019_S_4367,59,bl,12/5/11,11/26/12,2.00,0,1,3,0,...,0,0,0,0,0,0,0,0,1,0
34,141_S_4438,56,bl,2/6/12,NaN,6.00,0,1,5,0,...,2,1,2,1,2,1,0,1,3,2
35,130_S_4468,50,bl,2/16/12,NaN,4.00,0,1,3,0,...,0,0,0,0,0,0,0,0,1,0
36,009_S_4530,6,bl,2/22/12,5/30/12,6.00,0,0,5,1,...,2,1,2,1,1,2,1,1,3,2
37,128_S_4599,48,bl,3/28/12,NaN,0.00,0,0,0,0,...,1,0,2,1,0,1,0,0,0,1
38,100_S_4469,40,bl,4/18/12,8/26/13,3.00,0,0,3,0,...,0,0,1,0,0,1,0,0,1,0
39,070_S_4708,61,bl,5/23/12,6/29/12,5.00,0,1,7,0,...,0,0,3,1,2,2,0,0,2,0
40,136_S_4517,54,bl,5/11/12,NaN,4.00,0,0,4,0,...,1,1,1,1,0,1,1,1,1,1
41,013_S_4580,10,bl,4/26/12,NaN,2.00,0,0,2,0,...,0,0,2,0,1,1,0,0,2,0
42,070_S_4692,61,bl,5/17/12,6/29/12,6.00,0,0,8,0,...,2,1,2,1,2,2,1,1,4,2
43,036_S_4736,25,bl,6/19/12,NaN,5.00,0,0,8,0,...,2,0,1,1,1,2,0,0,3,2
44,053_S_4661,30,bl,6/12/12,NaN,5.00,0,0,3,0,...,0,1,1,1,1,2,0,1,0,0
45,023_S_5120,17,bl,6/20/13,NaN,4.00,0,1,3,1,...,1,0,1,1,1,2,0,0,1,1
46,023_S_5241,17,bl,10/25/13,NaN,5.00,0,1,10,0,...,2,0,0,1,2,1,0,0,2,2

In [5]:
merged_df.to_csv('/Users/cu135/Dropbox (Partners HealthCare)/studies/atrophy_seeds_2023/metadata/bl_adacorrelation_to_baseline_scores.csv')